server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /proyectobi/ {
    proxy_pass http://backend:3000/proyectobi/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /docs {
    proxy_pass http://backend:3000/docs;
  }

  location / {
    try_files $uri /index.html;
  }
}
